MCU = ATmega32U4
BOOTLOADER = atmel-dfu
F_CPU = 16000000
F_OPT = -O2

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
NKRO_ENABLE = yes